# Generated by Django 4.1.2 on 2022-11-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_contact_isread"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="username",
            field=models.CharField(default="none", max_length=15),
        ),
    ]
