# Generated by Django 4.1.2 on 2022-11-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_alter_signup_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="image",
            field=models.ImageField(default="", upload_to="images/img"),
        ),
    ]
