# Generated by Django 4.1.2 on 2022-11-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_signup_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes", name="upvotes", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="signup",
            name="upvotesuser",
            field=models.IntegerField(default=0),
        ),
    ]
