# Generated by Django 4.1.2 on 2022-11-16 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0009_upvotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="notes.signup"
            ),
        ),
    ]
