# Generated by Django 4.1.2 on 2022-11-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0010_alter_notes_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
