# Generated by Django 4.1.2 on 2022-11-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0014_notes_details_alter_notes_description_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup", name="contact", field=models.CharField(max_length=11),
        ),
    ]
