# Generated by Django 4.1.2 on 2022-11-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0015_alter_signup_contact"),
    ]

    operations = [
        migrations.RemoveField(model_name="signup", name="username",),
    ]
