# Generated by Django 4.1.2 on 2022-11-28 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0016_remove_signup_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="note",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="notes.notes",
            ),
        ),
    ]
